
<?php

//$this->headScript()->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js','text/javascript');

 
         $this->headScript()->appendFile($this->basePath() . '/js/bxslider/jquery.bxslider.min.js');
 $this->headLink()->appendStylesheet($this->basePath() . '/js/bxslider/jquery.bxslider.css');
?>


<script type="text/javascript" src="/js/tinymce/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    theme: "modern",
    plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    toolbar2: "print preview media | forecolor backcolor emoticons",
    image_advtab: true,
    templates: [
        {title: 'Test template 1', content: 'Test 1'},
        {title: 'Test template 2', content: 'Test 2'}
    ]
});
</script>

<?php
//$this->headTitle('View Post - ' . $post->getTitle());

$title =$post->getTitle();
$this->headTitle($title);

  $ree=strip_tags($post->getContent());
     $ree = preg_replace('/\s+/',' ',$ree);
     $des=substr($ree, 0, 500).'...';

$this->placeholder('description')->append($des);



$this->mainMenu()->setActiveItemId('ads');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Jobs')=>$this->url('empregos')
            ]);
        
       
?>

<a href="
    <?= $this->url('empregos', ['action'=>'index']); ?>">
    &lt;&lt; <?php echo $this->translate('Back to list of posts'); ?>
</a>

<h1>
    <?= $this->escapeHtml($post->getTitle()); ?>    
</h1>



<p>
    <?php echo $this->translate('Published:'); ?> <?= $this->escapeHtml(date('d-m-Y', strtotime($post->getDateCreated()))); ?>     
</p>

<p>    
    <?= $post->getContent(); ?>
</p>
<p>  
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- naview -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9468106265850608"
     data-ad-slot="4791223850"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</p>
<p>    
    <?php echo $this->translate('Visits : ').$post->getNumvisits(); ?>
</p>
<p>
    


<script>
    var hidden = false;
    function action() {
        hidden = !hidden;
        if(hidden) {
            document.getElementById('togglee').style.visibility = 'hidden';
        } else {
            document.getElementById('togglee').style.visibility = 'visible';
        }
    }
</script>
        <input type="button" id="toggler" value="Show Link or Email" onClick="action();" />
<!--<input type="button" id="togglee" value="Togglee" />-->
<div id="togglee"><?php echo $post->getContact(); ?></div>
    
    
</p>


  




 <script> 
 $(document).ready(function(){
//  $('.bxslidercv').bxSlider({
//  mode: 'fade',
//  captions: true,
////  slideMargin: '200',
//});
$('.bxslidercv').bxSlider({
  adaptiveHeight: true,
  mode: 'fade'
});
});



 </script>    
 
 <ul class="bxslidercv">
          <?php    
        $files = $imageManager->getSavedFiles($post->getId());
        ?> 
                 <?php
      foreach($files as $file)
  { ?>

   
     <li>  <img src="<?= $this->url('empregosimages', ['action'=>'file','id'=>$post->getId()], 
                    ['query'=>['name'=>$file, 'thumbnail'=>false]]); ?>"> </li>
                    		     		       

         
<?php     
        }//for each images
 ?>

</ul>

 <br>
<table>
<tr>
    <td>
    <div class="fb-share-button" data-href="http://www.etiju.com/empregosposts/view/<?php echo $post->getId(); ?>" data-layout="button_count"></div>
    

    </td>

</tr>
<tr>
    <td><br>
        <script src="//platform.linkedin.com/in.js" type="text/javascript">
  lang: en_US
</script>


<script type="IN/Share" data-url="http://www.etiju.com/empregosposts/view/<?php echo $post->getId(); ?>" data-counter="right"></script>



     </td>

</tr>
</table>
 