
<?php

//$this->headScript()->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js','text/javascript');

 
         $this->headScript()->appendFile($this->basePath() . '/js/bxslider/jquery.bxslider.min.js');
 $this->headLink()->appendStylesheet($this->basePath() . '/js/bxslider/jquery.bxslider.css');
?>


<script type="text/javascript" src="/js/tinymce/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    theme: "modern",
    plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    toolbar2: "print preview media | forecolor backcolor emoticons",
    image_advtab: true,
    templates: [
        {title: 'Test template 1', content: 'Test 1'},
        {title: 'Test template 2', content: 'Test 2'}
    ]
});
</script>

<?php
//$this->headTitle('View Post - ' . $post->getTitle());

$title =$post->getTitle();
$this->headTitle($title);

  $ree=strip_tags($post->getContent());
     $ree = preg_replace('/\s+/',' ',$ree);
     $des=substr($ree, 0, 500).'...';

$this->placeholder('description')->append($des);



$this->mainMenu()->setActiveItemId('ads');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Jobs')=>$this->url('empregos')
            ]);
        
       
?>

<a href="
    <?= $this->url('empregos', ['action'=>'index']); ?>">
    &lt;&lt; <?php echo $this->translate('Back to list of posts'); ?>
</a>

<h1>
    <?= $this->escapeHtml($post->getTitle()); ?>    
</h1>



<p>
    <?php echo $this->translate('Published:'); ?> <?= $this->escapeHtml(date('d-m-Y', strtotime($post->getDateCreated()))); ?>     
</p>

<p>    
    <?= $post->getContent(); ?>
</p>
<p>  

</p>
<p>    
    <?php echo $this->translate('Visits : ').$post->getNumvisits(); ?>
</p>
<p>


<button id='botao' class="btn btn-success"><?php echo $this->translate('Show Contact Link/Email'); ?></button>


<script>
  var button = document.getElementById('botao');

button.onclick = function() {
    var div = document.getElementById('newpost');
    if (div.style.display == 'none') {
        div.style.display = 'block';
    }
    else {
        div.style.display = 'none';
    }
};
</script>
       
<div id="newpost" style="display:none">
  <?php echo $post->getContact(); ?>
</div>
    
</p>

<hr>
<?php

    $user = $this->entityManager->getRepository(User\Entity\User::class)->findOneById($post->getIdentidade());
?>
<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></th>
            </tr>
            <tr>
                <th><?php echo $this->translate('E-mail:'); ?></th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></th>
            </tr>
            <tr>
                <th><?php echo $this->translate('Full Name:'); ?></th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></th>
            </tr>
      
       
              <tr>
<?php
        
           $files = $userImageManager->getSavedFiles($user->getId());
               
                                
            foreach($files as $file)
            { 
                ?>   
                        <th><?php echo $this->translate('Photo:'); ?></th>
                  <td>
              <img class="imagedropshadow" src="<?= $this->url('userimages', ['action'=>'file','id'=>$user->getId()],['query'=>['name'=>$file, 'thumbnail'=>true]]); ?>">
                 </td>
            <?php } ?>
                        

            
            </tr>
            
            
           
        </table>
    </div>
</div>
<br>



<hr>
<?php

    $empresa = $this->entityManager->getRepository(User\Entity\Empresas::class)->findOneByIdentidade($user->getId());

    if($empresa!=null)
    {
    ?>
<h1><?php echo $this->translate('View Company'); ?></h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            
                          <tr>
<?php
        
           $files = $empresaImageManager->getSavedFiles($empresa->getId());
               
                                
            foreach($files as $file)
            { 
                ?>    
               <th>
                   Logo :
               </th>
            <?php } ?>
                        
                      <td>   
            <img class="imagedropshadow" src="<?= $this->url('empresaimages', ['action'=>'file','id'=>$empresa->getId()],['query'=>['name'=>$file, 'thumbnail'=>true]]); ?>">
                
                    </td>
            
            </tr>
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($empresa->getId()) ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Company name:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getDesignacao()) ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Company description:'); ?></th>
                <td><?= $empresa->getDescricao() ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Company Address:'); ?></th>
                <td><?= $empresa->getEndereco() ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('E-mail:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getEmail()) ?></th>
            </tr>
        
            <tr>
                <th><?php echo $this->translate('WebSite:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getSite()) ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Facebook:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getFacebook()) ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Linkedin:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getLinkedin()) ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Twitter:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getTwitter()) ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Telefone:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getTelefone()) ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Fax:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getFax()) ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Date Created:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getDateCreated()) ?></th>
            </tr>
 
            

        </table>
    </div>
</div>
    <?php }?>

 <br>
<table>
<tr>
    <td>
    <div class="fb-share-button" data-href="http://www.etiju.com/empregosposts/view/<?php echo $post->getId(); ?>" data-layout="button_count"></div>
    

    </td>

</tr>
<tr>
    <td><br>
        <script src="//platform.linkedin.com/in.js" type="text/javascript">
  lang: en_US
</script>


<script type="IN/Share" data-url="http://www.etiju.com/empregosposts/view/<?php echo $post->getId(); ?>" data-counter="right"></script>



     </td>

</tr>
</table>
 