<?php
$this->headTitle($this->translate('Change Password'));

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Manage Users')=>$this->url('users'),
            $this->translate('Change Password')=>$this->url('users', ['action'=>'change-password', 'id'=>$user->getId()])
            ]);



$form->get('new_password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('Enter new password')
    ]);

$form->get('confirm_new_password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('Re-enter new password')
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();
?>

<h3><?php echo $this->translate('Change Password for'); ?> <?= $this->escapeHtml($user->getEmail()) ?></h3>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        

        
        <div class="form-group">
            <?php echo  $this->translate($this->formLabel($form->get('new_password'))); ?>
            <?= $this->formElement($form->get('new_password')); ?>
            <?= $this->formElementErrors($form->get('new_password')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo  $this->translate($this->formLabel($form->get('confirm_new_password'))); ?>
            <?= $this->formElement($form->get('confirm_new_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_new_password')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('csrf')); ?>
        
        <?php echo $this->translate($this->formElement($form->get('submit'))); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   


