<?php
$this->headTitle('Edit User');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Manage Users')=>$this->url('users'),
            $this->translate('Edit User')=>$this->url('users', ['action'=>'edit', 'id'=>$user->getId()])
            ]);

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('name@example.com')
    ]);

$form->get('full_name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('John Doe')
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('perfil')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue(_('Save'));

$form->prepare();
?>

<h1><?php echo $this->translate('Edit User'); ?> <?= $this->escapeHtml($user->getEmail()) ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?php echo $this->translate($this->formLabel($form->get('email'))); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->translate($this->formLabel($form->get('full_name'))); ?>
            <?= $this->formElement($form->get('full_name')); ?>
            <?= $this->formElementErrors($form->get('full_name')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->translate($this->formLabel($form->get('status'))); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
        
       <div class="form-group">
            <?php echo $this->translate($this->formLabel($form->get('perfil'))); ?>
            <?= $this->formElement($form->get('perfil')); ?>
            <?= $this->formElementErrors($form->get('perfil')); ?>                  
        </div>
        
        <?php echo $this->translate($this->formElement($form->get('submit'))); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

