<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
             $this->translate('Home')=>$this->url('home'),
            $this->translate('Manage Users')=>$this->url('users'),
            ]);
?>

<h1><?php echo $this->translate('Manage Users'); ?></h1>

<p>
<a class="btn btn-default" href="
    <?= $this->url('users', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <?php echo $this->translate('New User'); ?>
</a>

<a class="btn btn-default" href="
    <?= $this->url('users', ['action'=>'pesquisauserid']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <?php echo $this->translate('Search User ID'); ?>
</a>
</p>
<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>ADS NUM</th>
        <th><?php echo $this->translate('E-mail'); ?></th>
        <th><?php echo $this->translate('Full Name'); ?></th>
        <th><?php echo $this->translate('Date Created'); ?></th>
        <th><?php echo $this->translate('Status'); ?></th> 
        <th><?php echo $this->translate('Profile'); ?></th> 
        <th><?php echo $this->translate('Actions'); ?></th>        
    </tr>
         
    <?php foreach ($users as $user): ?>
    <?php          
    
        $conta=0; 
        

        
        $dql = "SELECT COUNT(p) FROM Empregos\Entity\Empregos p where p.identidade='".$user->getId()."'";
        $q4 =$entitymanager->createQuery($dql);
        $conta = $conta + $q4->getSingleScalarResult();

        
        
    ?>
    <tr>
        <td><?= $this->escapeHtml($user->getId()); ?></td>
        <td><?= $this->escapeHtml($conta); ?></td>
        <td>
            <a href="<?= $this->url('users', ['action'=>'view', 'id'=>$user->getId()]); ?>">
                <?= $this->escapeHtml($user->getEmail()); ?>
            </a> 
        </td>
        <td><?= $this->escapeHtml($user->getFullName()); ?></a> 
        </td>
        <td><?= $this->escapeHtml($user->getDateCreated()); ?></td>        
        <td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
        <td><?= $this->escapeHtml($user->getPerfilAsString()); ?></td>
        <td>
            <a class="btn btn-info" href="<?= $this->url('users', 
                    ['action'=>'edit', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> <?php echo $this->translate('Edit'); ?>
            </a>
            <a class="btn btn-default" href="<?= $this->url('users',
                    ['action'=>'change-passwordadmin', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-asterisk"></span> <?php echo $this->translate('Change Password'); ?>
            </a>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>

  <?= $this->paginationControl($this->users,
            'Sliding',
            'paginator.phtml', 
            ['route' => 'users']); ?>