<?php
$this->headTitle('Thank You');
?>

<div class="row">
<div class="col-md-offset-4 col-md-5">
<h1><?php echo $this->translate('Registration'); ?></h1>

<?php if ($id=='sent'): ?>
<p>    
    <?php echo $this->translate('A registration link has been sent to your email address.'); ?>
</p>
<?php elseif ($id=='invalid-email'): ?>
<p>
    <?php echo $this->translate('There is no user with such an email.'); ?>
    
</p>
<?php elseif ($id=='set'): ?>
<p>    
    <?php echo $this->translate('You registered successfully.'); ?>
</p>
<p>
    <?php echo $this->translate('Return to'); ?> <a href="<?= $this->url('login'); ?>"><?php echo $this->translate('login page'); ?></a>.
</p>
<?php elseif ($id=='failed'): ?>

    
    <?php echo $this->translate('Invalid registration key. If you allready registered and do not remember the password go '); ?>
    <a href="<?= $this->url('reset-password') ?>"><?php echo $this->translate('here'); ?></a> <?php echo $this->translate('and try reset your password.'); ?>
</p>
<?php endif; ?>
</div>
</div>    