<?php
$this->headTitle('Reset Password');

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('Email address')
    ]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-large btn-primary'
    ]);

$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>

        <h2><?php echo $this->translate('Reset Password'); ?></h2>

        <p><?php echo $this->translate('Enter your e-mail address below to reset your password'); ?></p>

        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>                              

        <?php // $this->formElement($form->get('captcha')); ?>
        
<!--<div class="form-group">-->
  
  <?= $this->formElement($form->get('captcha')); ?>
 
  <p class="help-block"><?php echo $this->translate('Enter the letters above as you see them.'); ?></p>
<!--</div>-->

        
    <?php echo $this->translate($this->formElement($form->get('submit'))); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
