<?php
$this->headTitle('View User');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Manage Users')=>$this->url('users'),
            $this->translate('View User')=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
            ]);


    //$flashMessenger = $this->flashMessenger();
    //if ($flashMessenger->hasMessages()) {
     //   echo $flashMessenger->getMessages();
   // }


if(isset($flash))
{
   foreach ($flash as $message)
   {
       
       echo $message;
   }   
}

//echo $flash['messages'];
?>


<?php // $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?php //$this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?php //$this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1><?php echo $this->translate('View User'); ?></h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></th>
            </tr>
            <tr>
                <th><?php echo $this->translate('E-mail:'); ?></th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></th>
            </tr>
            <tr>
                <th><?php echo $this->translate('Full Name:'); ?></th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></th>
            </tr>
            <tr>
                <th><?php echo $this->translate('Date Created:'); ?></th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th><?php echo $this->translate('Status:'); ?></th>
                <td><?= $this->escapeHtml($user->getStatusAsString()) ?></th>
            </tr>
            <tr>
                <th><?php echo $this->translate('Change Password:'); ?></th>
                <td>   <a class="btn btn-default" href="<?= $this->url('users',
                    ['action'=>'change-passwordadmin', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-asterisk"></span> <?php echo $this->translate('Change Password'); ?></td>
            </tr>
            <tr>
                <th><?php echo $this->translate('Profile:'); ?></th>
                <td><?= $this->escapeHtml($user->getPerfilAsString()) ?></th>
            </tr>
            <?php if($user->getPerfil()==2) { ?>
            <tr>
            <th><?php echo $this->translate('PRO account will expire at:'); ?></th>
            <td><?= $this->escapeHtml($user->getProexpiredate()) ?></td>
            </tr>
            <?php } ?>
              <tr>
<?php
        
           $files = $userImageManager->getSavedFiles($user->getId());
               
                                
            foreach($files as $file)
            { 
                ?>    <th>
              <img class="imagedropshadow" src="<?= $this->url('userimages', ['action'=>'file','id'=>$user->getId()],['query'=>['name'=>$file, 'thumbnail'=>true]]); ?>">
                 </th>
            <?php } ?>
                        
                      <td>   
            <a class="btn btn-info" href="<?= $this->url('userimages', 
                    ['action'=>'index', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> <?php echo $this->translate('User Photo'); ?>
            </a>
                    
                    </td>
            
            </tr>
            
            
            <tr>
                <?php
              
                             // Find a user with such ID.
                  $empresa = $this->entityManager->getRepository(User\Entity\Empresas::class)->getIdentidade($user->getId());
                  
                  if(!isset($empresa)){
                      
                      return;
                      
                  }
                  
        
  
                           
                ?>
                     <a class="btn btn-info" href="<?= $this->url('empresas', 
                    ['action'=>'index', 'id'=>$empresa->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> <?php echo $this->translate('Create Company'); ?>
            </a>
                
            </tr>
        </table>
    </div>
</div>