<?php
$this->headTitle('View User');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Manage Users')=>$this->url('users'),
            $this->translate('View User')=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
            ]);


    //$flashMessenger = $this->flashMessenger();
    //if ($flashMessenger->hasMessages()) {
     //   echo $flashMessenger->getMessages();
   // }


if(isset($flash))
{
   foreach ($flash as $message)
   {
       
       echo $message;
   }   
}

//echo $flash['messages'];
?>


<?php // $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?php //$this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?php //$this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1><?php echo $this->translate('View User'); ?></h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></th>
            </tr>
            <tr>
                <th><?php echo $this->translate('E-mail:'); ?></th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></th>
            </tr>
            <tr>
                <th><?php echo $this->translate('Full Name:'); ?></th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></th>
            </tr>
            <tr>
                <th><?php echo $this->translate('Date Created:'); ?></th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th><?php echo $this->translate('Status:'); ?></th>
                <td><?= $this->escapeHtml($user->getStatusAsString()) ?></th>
            </tr>
            <tr>
                <th><?php echo $this->translate('Change Password:'); ?></th>
                <td>   <a class="btn btn-default" href="<?= $this->url('users',
                    ['action'=>'change-passwordadmin', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-asterisk"></span> <?php echo $this->translate('Change Password'); ?></td>
            </tr>
            <tr>
                <th><?php echo $this->translate('Profile:'); ?></th>
                <td><?= $this->escapeHtml($user->getPerfilAsString()) ?></th>
            </tr>
            <?php if($user->getPerfil()==2) { ?>
            <tr>
            <th><?php echo $this->translate('PRO account will expire at:'); ?></th>
            <td><?= $this->escapeHtml($user->getProexpiredate()) ?></td>
            </tr>
            <?php } ?>
              <tr>
<?php
        
           $files = $userImageManager->getSavedFiles($user->getId());
               
                                
            foreach($files as $file)
            { 
                ?>    <th>
              <img class="imagedropshadow" src="<?= $this->url('userimages', ['action'=>'file','id'=>$user->getId()],['query'=>['name'=>$file, 'thumbnail'=>true]]); ?>">
                 </th>
            <?php } ?>
                        
                      <td>   
            <a class="btn btn-info" href="<?= $this->url('userimages', 
                    ['action'=>'index', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> <?php echo $this->translate('User Photo'); ?>
            </a>
                    
                    </td>
            
            </tr>
            
            
            <tr>
                <th><?php echo $this->translate('Company:'); ?></th>
                <td>
                <?php
              
            
               // $empresa = $entityManager->createQuery("SELECT u FROM User\Entity\Empresas u where u.identidade='".$user->getId()."'");
                //$empresa=$empresa->getResult();
                
                         // Look for the user with such email.
                $empresa = $this->entityManager->getRepository(User\Entity\Empresas::class)
                        ->findOneByIdentidade($user->getId()); 
                if($empresa==null){
                      
                  ?>
                  <p>
                        <a class="btn btn-default" href="
                            <?= $this->url('empresas', ['action'=>'add']); ?>">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <?php echo $this->translate('New Company'); ?>
                        </a>
                   </p>
                        
                   <?php
                   
                      
                  }else
                  {?>
                   
                        <a class="btn btn-info" href="<?= $this->url('empresas',['action'=>'view', 'id'=>$empresa->getId()]); ?>">
                           <span class="glyphicon glyphicon-pencil" ></span> <?php echo $this->translate('Your Company'); ?>
                        </a>
                
                      <?php
                      
                  } 
                      
                  
        
  
                           
                ?>
                
</td>
    
            </tr>
        </table>
    </div>
</div>