<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
             $this->translate('Home')=>$this->url('home'),
            $this->translate('Manage Companies')=>$this->url('empresas'),
            ]);
?>

<h1><?php echo $this->translate('Manage Companies'); ?></h1>

<p>
<a class="btn btn-default" href="
    <?= $this->url('empresas', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <?php echo $this->translate('New Company'); ?>
</a>
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
 
        <th><?php echo $this->translate('E-mail'); ?></th>
        <th><?php echo $this->translate('Company Name'); ?></th>
        <th><?php echo $this->translate('Date Created'); ?></th>
        <th><?php echo $this->translate('Actions'); ?></th>        
    </tr>
         
    <?php foreach ($users as $empresa): ?>

    <tr>
        <td><?= $this->escapeHtml($empresa->getId()); ?></td>
           <td>
            <a href="<?= $this->url('empresas', ['action'=>'view', 'id'=>$empresa->getId()]); ?>">
                <?= $this->escapeHtml($empresa->getEmail()); ?>
            </a> 
        </td>
       
        <td><?= $this->escapeHtml($empresa->getDesignacao()); ?></a> 
        </td>
        <td><?= $this->escapeHtml($empresa->getDateCreated()); ?></td>        
   
        <td>
            <a class="btn btn-info" href="<?= $this->url('empresas', 
                    ['action'=>'edit', 'id'=>$empresa->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> <?php echo $this->translate('Edit'); ?>
            </a>
          
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>

  <?= $this->paginationControl($this->users,
            'Sliding',
            'paginator.phtml', 
            ['route' => 'empresas']); ?>