<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
             $this->translate('Home')=>$this->url('home'),
            $this->translate('Manage Companies')=>$this->url('empresas'),
            ]);
?>

<h1><?php echo $this->translate('Manage Companies'); ?></h1>

<p>
<a class="btn btn-default" href="
    <?= $this->url('empresas', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <?php echo $this->translate('New Company'); ?>
</a>
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>ADS NUM</th>
        <th><?php echo $this->translate('E-mail'); ?></th>
        <th><?php echo $this->translate('Full Name'); ?></th>
        <th><?php echo $this->translate('Date Created'); ?></th>
        <th><?php echo $this->translate('Status'); ?></th> 
        <th><?php echo $this->translate('Profile'); ?></th> 
        <th><?php echo $this->translate('Actions'); ?></th>        
    </tr>
         
    <?php foreach ($users as $user): ?>
    <?php          
    
        $conta=0; 
        

        
        $dql = "SELECT COUNT(p) FROM Empregos\Entity\Empregos p where p.identidade='".$user->getId()."'";
        $q4 =$entitymanager->createQuery($dql);
        $conta = $conta + $q4->getSingleScalarResult();

        
        
    ?>
    <tr>
        <td><?= $this->escapeHtml($user->getId()); ?></td>
       
       
        <td><?= $this->escapeHtml($user->getDesignacao()); ?></a> 
        </td>
        <td><?= $this->escapeHtml($user->getDateCreated()); ?></td>        
   
        <td>
            <a class="btn btn-info" href="<?= $this->url('empresas', 
                    ['action'=>'edit', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> <?php echo $this->translate('Edit'); ?>
            </a>
          
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>

  <?= $this->paginationControl($this->users,
            'Sliding',
            'paginator.phtml', 
            ['route' => 'empresas']); ?>