<?php
$this->headTitle('View Company');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
           // $this->translate('Manage Companies')=>$this->url('empresas'),
            $this->translate('View Company')=>$this->url('empresas', ['action'=>'view', 'id'=>$empresa->getId()])
            ]);


    //$flashMessenger = $this->flashMessenger();
    //if ($flashMessenger->hasMessages()) {
     //   echo $flashMessenger->getMessages();
   // }


if(isset($flash))
{
   foreach ($flash as $message)
   {
       
       echo $message;
   }   
}

//echo $flash['messages'];
?>


<?php // $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?php //$this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?php //$this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1><?php echo $this->translate('View Company'); ?></h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th><?php echo $this->translate('Edit:'); ?></th>
                <td>
                    <a class="btn btn-info" href="<?= $this->url('empresas', 
                        ['action'=>'edit', 'id'=>$empresa->getId()]); ?>">
                        <span class="glyphicon glyphicon-pencil" ></span> <?php echo $this->translate('Edit'); ?>
                     </a>
          
                </td>  
            </tr>
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($empresa->getId()) ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Company name:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getDesignacao()) ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Company description:'); ?></th>
                <td><?= $empresa->getDescricao() ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Company Address:'); ?></th>
                <td><?= $empresa->getEndereco() ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('E-mail:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getEmail()) ?></th>
            </tr>
        
            <tr>
                <th><?php echo $this->translate('WebSite:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getSite()) ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Facebook:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getFacebook()) ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Linkedin:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getLinkedin()) ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Twitter:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getTwitter()) ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Telefone:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getTelefone()) ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Fax:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getFax()) ?></th>
            </tr>
            
            <tr>
                <th><?php echo $this->translate('Date Created:'); ?></th>
                <td><?= $this->escapeHtml($empresa->getDateCreated()) ?></th>
            </tr>
 
            

        </table>
    </div>
</div>