<?php
$this->headTitle('Company Logo Image Gallery');

$this->mainMenu()->setActiveItemId('ads');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Users')=>$this->url('users'),
            $this->translate('CV Gallery') => $this->url('curriculospdf')
            ]);
?>

<h1> <?php echo $this->translate('CV Gallery'); ?></h1>

<p>
    
    <?php echo $this->translate('This page displays the list of uploaded images.'); ?>
</p>

<p>
    <a href="<?= $this->url('curriculospdf', ['action'=>'upload','id'=>$postId]); ?>" 
       class="btn btn-primary" role="button"><?php echo $this->translate('Upload More'); ?></a>
</p>

<hr/>

<?php if(count($files)==0): ?>

<p>
    <i><?php echo $this->translate('There are no files to display.'); ?></i>
</p>

<?php else: ?>

<div class="row">
    <div class="col-sm-6 col-md-12">

        <?php foreach($files as $file): ?>  

        
            <p>
            <a  href="<?= $this->url('curriculospdf', ['action'=>'file','id'=>$postId], 
                    ['query'=>['name'=>$file]]); ?>"><?php echo $file; ?></a>
            
            
                <!--<h3><?php echo $file; ?></h3>-->                    
                
                <p>
                    <a  href="<?= $this->url('curriculospdf',  
                            ['action'=>'deletefile','id'=>$postId], ['query'=>['name'=>$file]]); ?>" 
                            class="btn btn-default" role="button"><?php echo $this->translate('Delete File'); ?></a>
                </p>
           
        
        <?php endforeach; ?>
    </div>
</div>

<hr/>

<?php endif; ?>
