

<?php
$this->headTitle('Posts');

$this->mainMenu()->setActiveItemId('ads');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Jobs')=>$this->url('empregos')
            ]);
?>
<p align="center">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- anuncioproauto -->
<ins class="adsbygoogle"
     style="display:inline-block;width:320px;height:100px"
     data-ad-client="ca-pub-9468106265850608"
     data-ad-slot="8799465059"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</p>
<h1><?php echo $this->translate('Posts'); ?></h1>
<?php 


if($expirados>0){
?>
<p style="color:red"><?php echo $this->translate('You have :').$expirados.$this->translate(' posts expired, to prevent them from being deleted, edit each expired post and set status to pending approval'); ?></p>
<?php } ?>


<p>
    
    <?php 
    if($contaparamember>=1 && $perfil== User\Entity\User::PERFIL_MEMBER){
    ?>
    <a class="btn btn-primary" href="<?= $this->url('application',
                    ['action'=>'settings']); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('To place more ads go to Settings and become PRO'); ?>
    </a>
    <?php } else { ?>
    
    <a class="btn btn-primary" href="<?= $this->url('empregosposts',
                    ['action'=>'add']); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Add New Post'); ?>
    </a>
    
    <?php } ?>
    
    <a class="btn btn-primary" href="<?= $this->url('empregosposts',
                    ['action'=>'myadmin']); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Manage my Posts'); ?>
    </a>
        <a class="btn btn-primary" href="<?= $this->url('empregospesquisa',
                    ['action'=>'pesquisa']); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Search'); ?>
    </a>
    

 

</p>
<div class="row">
    
    <div class="col-md-20">
    <?php foreach($posts as $post): ?>
        <table>
            
            <tr>
        
                <td>
                            <?php    
     
             
        $user = $entityManager->getRepository(\User\Entity\User::class)
                        ->findOneById($post->getIdentidade());
        
        if(isset($user))
        {
        
        $empresa = $entityManager->getRepository(\User\Entity\Empresas::class)
                        ->findOneByIdentidade($user->getId());
        if(isset($empresa)){
               $files = $imageManager->getSavedFiles($empresa->getId());
         }
        }
        //echo $empresa->getId();
        
        ?> 
                  
        <?php 
        if(isset($empresa)){
            
            
          foreach($files as $file): 
           
        ?>
                 
                    <img class="imagedropshadow"  src="<?= $this->url('empresaimages', ['action'=>'file','id'=>$empresa->getId()], 
                    ['query'=>['name'=>$file, 'thumbnail'=>true]]); ?>">
   
        <?php
        endforeach; 
        
        
            }else
                
            { ?>
                
                <img style="width: 280px;height: 240px;" src=<?php echo $this->basePath() .'/img/thejoblogo4.png'?>
                     
                     
                <?php
            }
        ?>
            </td>
            
            <td>

   
        
    <h3>
        <a href="<?= $this->url('empregosposts', ['action'=>'view', 'id'=>$post->getId()]); ?>">
            <?= $this->escapeHtml($post->getTitle()); ?>
        </a>    
    </h3>
        

        
   
         <?php echo $this->translate('Published:'); ?><?= $this->escapeHtml(date('d-m-Y', strtotime($post->getDateCreated()))); ?> 
        
       
     </td>
        </tr>
</table>

    <?php endforeach; ?>

    </div>

  
</div>

  <?= $this->paginationControl($this->posts,
            'Sliding',
            'paginator.phtml', 
            ['route' => 'empregos']); ?>
