

<?php
$this->headTitle('Posts');

$this->mainMenu()->setActiveItemId('ads');

$this->pageBreadcrumbs()->setItems([
        $this->translate('Jobs')=>$this->url('empregos'), 
        $this->translate('Search')=>$this->url('empregosposts', ['action'=>'pesquisa'])
            ]);


?>

<h1><?php echo $this->translate('Posts'); ?></h1>
<p>
    <a class="btn btn-primary" href="<?= $this->url('empregosposts',
                    ['action'=>'add']); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Add New Post'); ?>
    </a>
    <a class="btn btn-primary" href="<?= $this->url('empregosposts',
                    ['action'=>'myadmin']); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Manage my Posts'); ?>
    </a>
    
            <a class="btn btn-primary" href="<?= $this->url('empregospesquisa',
                    ['action'=>'pesquisa']); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Search'); ?>
    </a>

 

</p>

<?php


$form = $this->form;
$form->get('search')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('Enter you search here')
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>


<p>
    <?php echo $this->translate('Please fill out the following form and click the '); ?>
     <i><?php echo $this->translate('Search'); ?></i> <?php echo $this->translate('button'); ?>.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?php echo $this->translate($this->formLabel($form->get('search'))); ?>
            <?= $this->formElement($form->get('search')); ?>
            <?= $this->formElementErrors($form->get('search')); ?>                  
        </div>
        
  
        
        <?php echo $this->translate($this->formElement($form->get('submit'))); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   



<div class="row">
    
    <div class="col-md-20">

        
    <?php 
    if($posts!=null)
    {
    
    foreach($posts as $post): ?>
        
    <h3>
        <a href="<?= $this->url('empregosposts', ['action'=>'view', 'id'=>$post->getId()]); ?>">
            <?= $this->escapeHtml($post->getTitle()); ?>
        </a>    
    </h3>
        
     <?php    
        $files = $imageManager->getSavedFiles($post->getId());
        ?>  
        
        <p>
   
         <?php $conta=0; ?>
       <?php foreach($files as $file): 
           
        if($conta==0){ ?>
             <a href="<?php echo $this->url('empregosposts', ['action'=>'view', 'id'=>$post->getId()]); ?>">
            
       <?php }
           ?>
    
        
            <img class="imagedropshadow" src="<?= $this->url('empregosimages', ['action'=>'file','id'=>$post->getId()], 
                    ['query'=>['name'=>$file, 'thumbnail'=>true]]); ?>">
   
          <?php    if($conta==0){ ?>
              </a> 
            
       <?php }
           ?>
        <?php
           if($conta==2)
           {
            break;
           }
        $conta=$conta+1;
        endforeach; ?>
    
   

    </p>
    <p>
         <?php echo $this->translate('Published:'); ?><?= $this->escapeHtml(date('d-m-Y', strtotime($post->getDateCreated()))); ?> 
        
       
    </p>    
        


    <?php endforeach; ?>

    </div>

  
</div>

  <?php 
  //echo $search_by;
  echo $this->paginationControl($this->posts,
            'Sliding',
            'paginators.phtml', 
            ['route' => 'empregospaginator-search','search_by' => $search_by]);
  
          //ERR_CACHE_MISS isto resolve
      header('Cache-Control: no cache');

    }else{ echo $this->translate('No results found');}
    
    ?>
