

<?php
$this->headTitle('Posts');

$this->mainMenu()->setActiveItemId('ads');

$this->pageBreadcrumbs()->setItems([
        $this->translate('Jobs')=>$this->url('empregos'), 
        $this->translate('Search')=>$this->url('empregosposts', ['action'=>'pesquisa'])
            ]);


?>

<h1><?php echo $this->translate('Posts'); ?></h1>
<p>
    <?php 
    if($contaparamember>=1 && $perfil== User\Entity\User::PERFIL_MEMBER){
    ?>
    <a class="btn btn-primary" href="<?= $this->url('application',
                    ['action'=>'settings']); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('To place more ads go to Settings and become PRO'); ?>
    </a>
    <?php } else { ?>
    
    <a class="btn btn-primary" href="<?= $this->url('empregosposts',
                    ['action'=>'add']); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Add New Post'); ?>
    </a>
    
    <?php } ?>
    <a class="btn btn-primary" href="<?= $this->url('empregosposts',
                    ['action'=>'myadmin']); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Manage my Posts'); ?>
    </a>
    
            <a class="btn btn-primary" href="<?= $this->url('empregospesquisa',
                    ['action'=>'pesquisa']); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Search'); ?>
    </a>

 

</p>

<?php


$form = $this->form;
$form->get('search')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('Enter you search here')
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>


<p>
    <?php echo $this->translate('Please fill out the following form and click the '); ?>
     <i><?php echo $this->translate('Search'); ?></i> <?php echo $this->translate('button'); ?>.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?php echo $this->translate($this->formLabel($form->get('search'))); ?>
            <?= $this->formElement($form->get('search')); ?>
            <?= $this->formElementErrors($form->get('search')); ?>                  
        </div>
        
  
        
        <?php echo $this->translate($this->formElement($form->get('submit'))); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   



<div class="row">
    
    <div class="col-md-20">

        
    <?php 
    if($posts!=null)
    {
    
     foreach($posts as $post): ?>
        <table>
            
            <tr>
        
                <td>
                            <?php    
     
             
        $user = $entityManager->getRepository(\User\Entity\User::class)
                        ->findOneById($post->getIdentidade());
        
        if(isset($user))
        {
        
        $empresa = $entityManager->getRepository(\User\Entity\Empresas::class)
                        ->findOneByIdentidade($user->getId());
        if(isset($empresa)){
               $files = $imageManager->getSavedFiles($empresa->getId());
         }
        }
        //echo $empresa->getId();
        
        ?> 
                  
        <?php 
        if(isset($empresa)){
            
            
          foreach($files as $file): 
           
        ?>
                 
                    <img class="imagedropshadow"  src="<?= $this->url('empresaimages', ['action'=>'file','id'=>$empresa->getId()], 
                    ['query'=>['name'=>$file, 'thumbnail'=>true]]); ?>">
   
        <?php
        endforeach; 
        
        
            }else
                
            { ?>
                
                    <img style="width: 280px;height: 240px;" src=<?php echo $this->basePath() .'/img/thejoblogo4.png'?>
                     
                     
                <?php
            }
        ?>
            </td>
            
            <td>

   
        
    <h3>
        <a href="<?= $this->url('empregosposts', ['action'=>'view', 'id'=>$post->getId()]); ?>">
            <?= $this->escapeHtml($post->getTitle()); ?>
        </a>    
    </h3>
        

        
   
         <?php echo $this->translate('Published:'); ?><?= $this->escapeHtml(date('d-m-Y', strtotime($post->getDateCreated()))); ?> 
        
       
     </td>
        </tr>
</table>

    <?php endforeach; ?>
    </div>

  
</div>

  <?php 
  //echo $search_by;
  echo $this->paginationControl($this->posts,
            'Sliding',
            'paginators.phtml', 
            ['route' => 'empregospaginator-search','search_by' => $search_by]);
  
          //ERR_CACHE_MISS isto resolve
      header('Cache-Control: no cache');

    }else{ echo $this->translate('No results found');}
    
    ?>
