<?php
$this->headTitle('Upload a New Logo Image');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Home') => $this->url('home'),
            $this->translate('Company Logo Image Gallery') => $this->url('empresaimages')
            ]);

$form = $this->form;
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

if($message!='')
{
    
  echo $message; 
  return;
    
}
?>

<h1><?php echo $this->translate('Upload a New Logo Image'); ?></h1>

<p>
    <?php echo $this->translate('Please fill out the following form and press the') ?> <i><?php echo $this->translate('Upload'); ?></i> <?php echo $this->translate('button'); ?>.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('file')); ?>
            <?= $this->formElement($form->get('file')); ?>
            <?= $this->formElementErrors($form->get('file')); ?>                  
        </div>
                
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>    