




 <div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
           
            <div class="panel-body">
<p align="center">

</p>

               
            </div>
        </div>
    </div>



 
    
    
    <div class="col-md-4">
        <div class="panel panel-default">
           
            <div class="panel-body">   
                <center>
                    <br>
		<p>
                 <a class="btn btn-success" href="<?= $this->url('register'); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Register Free'); ?>
                </a>
                </p>  <br>  <br> 
                </center>
            </div>
        </div>
    </div>
    
   
        <div class="col-md-4">
        <div class="panel panel-default">
           
            <div class="panel-body">               
	<p align="center">

</p>            
            </div>
        </div>
    </div>
     
        
    
</div>

 <div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
           
            <div class="panel-body">
<p align="center">

</p>

               
            </div>
        </div>
    </div>



 
    
    
    <div class="col-md-4">
        <div class="panel panel-default">
           
            <div class="panel-body">   
                <center>
                    <br>
		<p>
                 <a class="btn btn-success" href="<?= $this->url('empregos'); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Jobs'); ?>
                </a>
                </p>  <br>  <br> 
                </center>
            </div>
        </div>
    </div>
    
   
        <div class="col-md-4">
        <div class="panel panel-default">
           
            <div class="panel-body">               
	<p align="center">

</p>            
            </div>
        </div>
    </div>
     
        
    
</div>
 
