




 <div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
           
            <div class="panel-body">
<p align="center">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- thejoboard -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9468106265850608"
     data-ad-slot="9832770653"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</p>

               
            </div>
        </div>
    </div>



 
    
    
    <div class="col-md-4">
        <div class="panel panel-default">
           
            <div class="panel-body">   
                <center>
                    <br>
		<p>
                 <a class="btn btn-success" href="<?= $this->url('register'); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Register Free'); ?>
                </a>
                    
                                  <a class="btn btn-success" href="<?= $this->url('empregos'); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Jobs'); ?>
                </a>
                </p>  <br>  <br> 
                </center>
            </div>
        </div>
    </div>
    
   
        <div class="col-md-4">
        <div class="panel panel-default">
           
            <div class="panel-body">               
	<p align="center">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- thejoboard -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9468106265850608"
     data-ad-slot="9832770653"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</p>            
            </div>
        </div>
    </div>
     
        
    
</div>