



<?php


 $this->headScript()->appendFile($this->basePath() . '/js/box/jquery.bxslider.min.js');
 $this->headLink()->appendStylesheet($this->basePath() . '/js/box/jquery.bxslider.min.css');
 
 ?>


<script> 
     $(document).ready(function(){
 

 $('.bxslider').bxSlider({
    
  minSlides: 5,
  maxSlides: 10,
  slideWidth: 1900,
  slideMargin: 5,
  ticker: true,
  speed: 10000
});



});
 </script> 


 <ul class="bxslider">

<li><img src="<?php echo $this->basePath('img/logo.png') ?>" style="background:no-repeat; background-size:contain; background-position: center;" alt="www.etiju.com" ></li>


</ul>
 <div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
           
            <div class="panel-body">
<p align="center">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- index -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9468106265850608"
     data-ad-slot="1720006250"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</p>

               
            </div>
        </div>
    </div>



 
    
    
    <div class="col-md-4">
        <div class="panel panel-default">
           
            <div class="panel-body">   
                <center>
                    <br>
		<p>
                 <a class="btn btn-success" href="<?= $this->url('register'); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Register Free'); ?>
                </a>
                </p>  <br>  <br> 
                </center>
            </div>
        </div>
    </div>
    
   
        <div class="col-md-4">
        <div class="panel panel-default">
           
            <div class="panel-body">               
	<p align="center">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- index -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9468106265850608"
     data-ad-slot="1720006250"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</p>            
            </div>
        </div>
    </div>
     
        
    
</div>

 <div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
           
            <div class="panel-body">
<p align="center">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- index -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9468106265850608"
     data-ad-slot="1720006250"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</p>

               
            </div>
        </div>
    </div>



 
    
    
    <div class="col-md-4">
        <div class="panel panel-default">
           
            <div class="panel-body">   
                <center>
                    <br>
		<p>
                 <a class="btn btn-success" href="<?= $this->url('empregos'); ?>">
                <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Jobs'); ?>
                </a>
                </p>  <br>  <br> 
                </center>
            </div>
        </div>
    </div>
    
   
        <div class="col-md-4">
        <div class="panel panel-default">
           
            <div class="panel-body">               
	<p align="center">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- index -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9468106265850608"
     data-ad-slot="1720006250"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</p>            
            </div>
        </div>
    </div>
     
        
    
</div>
 
