<?php
$this->headTitle('Location');

$this->mainMenu()->setActiveItemId('about');

$this->pageBreadcrumbs()->setItems([
             $this->translate('Home')=>$this->url('home'),
             $this->translate('Location')=>$this->url('localizacao'),
            ]);
?>

<h2><?php echo $this->translate('Location'); ?></h2>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th><?php echo $this->translate('Location'); ?>:</th>
                <td>Praça Marquês de Marialva, Cantanhede, Coimbra, Portugal</td>
            </tr>
            <tr>
                <th><?php echo $this->translate('Map'); ?> :</th>
                <td><img src="<?php echo $this->basePath() .'/img/cantanhede.png'?>" style="size:contain;" alt="Cantanhede"/></td>
            </tr>
        
        </table>
    </div>
</div>


