<?php
$this->headTitle('Settings');

$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
             $this->translate('Home')=>$this->url('home'),
             $this->translate('Settings')=>$this->url('application', ['action'=>'settings']),
            ]);

if(isset($flash))
{
   foreach ($flash as $message)
   {
       
       echo $message;
   }   
}
?>

<h2><?php echo $this->translate('Settings'); ?></h2>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></td>
            </tr>
            <tr>
                <th><?php echo $this->translate('E-mail'); ?> :</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></td>
            </tr>
            <tr>
                <th><?php echo $this->translate('Full Name'); ?> :</th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></td>
            </tr>
            <tr>
                <th><?php echo $this->translate('Date Created'); ?> :</th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></td>
            </tr>
              <tr>
                <th><?php echo $this->translate('Email Subscription'); ?> :</th>
                <td><?php if($user->getUnsubscribe()==1){ echo $this->translate('User Unsubscribed'); } else { echo $this->translate('User Subscribed');} ?></td>
            </tr>
            <tr>
                <th><?php echo $this->translate('Email Subscription'); ?> :</th>
                <td><?php if($user->getUnsubscribe()==1){ ?>
                    
                    <a class="btn btn-success" href="<?= $this->url('subscribe',
                    ['action'=>'subscribe', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-asterisk"></span> <?php echo $this->translate('Subscribe'); ?>



                <?php } else { ?>
                                    <a class="btn btn-danger" href="<?= $this->url('unsubscribe',
                    ['action'=>'unsubscribe', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-asterisk"></span> <?php echo $this->translate('Unsubscribe'); ?>
                
                <?php } ?>
                
                
                </td>
            </tr>
            <tr>
                <th><?php echo $this->translate('Profile:'); ?></th>
                <td><?= $this->escapeHtml($user->getPerfilAsString()) ?></td>
            </tr>
            <tr>
                <th><?php echo $this->translate('Change Password:'); ?></th>
                <td>   <a class="btn btn-default" href="<?= $this->url('users',
                    ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-asterisk"></span> <?php echo $this->translate('Change Password'); ?></td>
            </tr>
                     
            </a>
            <?php if($user->getPerfil()==0) { ?>
            <tr>
                <th><?php echo $this->translate('Become PRO for 25 Euros a Year:'); ?></th>
                <td><a href="<?php echo $this->url('paypalone');?>"><img src=<?php echo $this->basePath() .'/img/paypal.jpg'?> alt="Paypal"/></a></td>
            </tr>
            <?php } ?>
            <?php if($user->getPerfil()==2) { ?>
            <tr>
            <th><?php echo $this->translate('Your PRO account will expire at:'); ?></th>
            <td><?= $this->escapeHtml($user->getProexpiredate()) ?></td>
            </tr>
            <?php } ?>
            <tr>
                <th>Photo </th>
           <td>
           <?php
            
           $files = $userImageManager->getSavedFiles($user->getId());
               
                                
            foreach($files as $file)
            { 
            ?>
              <img class="imagedropshadow" src="<?= $this->url('userimages', ['action'=>'file','id'=>$user->getId()],['query'=>['name'=>$file, 'thumbnail'=>true]]); ?>">
                 
            <?php } ?>
                        
                        
            <a class="btn btn-info" href="<?= $this->url('userimages', 
                    ['action'=>'index', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> <?php echo $this->translate('User Photo'); ?>
            </a>
                    
                    </td>
            
            </tr>
            
            
            
        </table>
    </div>
</div>